#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --source_id="prebuilt"  --dest_dir="$install_dir/sources"
ynh_setup_source --source_id="dotnet" --dest_dir="$install_dir/dotnet"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

ynh_hide_warnings yunohost firewall allow Both 53

yunohost service add "$app" --description="Technitium DNS Server" --log="/var/log/technitium/$app.log" --needs_exposed_ports="53"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate /var/log/technitium/dns

ynh_config_add --template="dnsmasq.conf" --destination="/etc/dnsmasq.d/$app.conf"

ynh_systemctl --service="dnsmasq" --action="restart"

#=================================================
# ADD A CRON JOB
#=================================================
ynh_config_add --template="logsymlink.cron" --destination="/etc/cron.d/$app"
chown root: "/etc/cron.d/$app"
chmod 644 "/etc/cron.d/$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================

ynh_systemctl --service="$app" --action="start" --log_path=systemd --wait_until="Technitium DNS Server was started successfully"

#=================================================
# LINK LOGS
#=================================================
ln -sf $(ls -t /var/log/technitium/dns/*.log | head -n 1) /var/log/technitium/technitium-dns.log

#=================================================
# SET LOCAL ENDPOINT IP(S)
#=================================================
ipv4=$(ip -4 route get 1.1.1.1 | grep -oP 'src \K\S+' || echo "")
ipv6=$(ip -6 route get 2606:4700:4700::1111 2>/dev/null | grep -oP 'src \K\S+' || echo "")

if [ -n "$ipv6" ]; then
    endpoints="$ipv4:53,[$ipv6]:53"
else
    endpoints="$ipv4:53"
fi

mytoken1=$(curl -s "http://127.0.0.1:5380/api/user/createToken?user=admin&pass=admin&tokenName=mytoken1" | jq -r '.token')
curl -s "http://localhost:5380/api/settings/set?dnsServerLocalEndPoints=$endpoints&Token=$mytoken1"

#=================================================
# RESTART SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="restart" --log_path=systemd --wait_until="Technitium DNS Server was started successfully"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
